spring.profiles.active: local

spring:
  jmx:
    enabled: false
  main:
    allow-bean-definition-overriding: true
cdn:
    gcs:
       appName: <please input your appname here>
       appId: <please input your appid - project id - here>
       bucket: <please input your bucket here>
       rootPath: <please input root path of your objects here>
       serviceAccountEmail: <please input your google service account here>
       serviceAccountPrivateKey: <please input your private key json file here>
