spring.profiles.active: local

spring:
  jmx:
    enabled: false
  main:
    allow-bean-definition-overriding: true
cdn:
    gcs:
       appName: OneDev
       appId: onedev-271406
       bucket: onedevtest
       rootPath: local
       serviceAccountEmail: ondevservice@onedev-271406.iam.gserviceaccount.com
       serviceAccountPrivateKey: onedev-271406-a388fa48a116.json
